version: '3.8'

services:
  web:
    image: yooingyu/anifarm:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - KMA_API_KEY=${KMA_API_KEY}
      - KAMIS_API_KEY=${KAMIS_API_KEY}
      - DATAENCODING_API_KEY=${DATAENCODING_API_KEY}
      - DATADECODING_API_KEY=${DATADECODING_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - YOUNG_API_KEY=${YOUNG_API_KEY}
      - INFOMATION_API_KEY=${INFOMATION_API_KEY}
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
