version: '3.8'

services:
  app_deploy_web:
    image: anifarm_deploy_web
    container_name: anifarm_deploy_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge 