version: '3.8'

services:
  web:
    image: yooingyu/anifarm:latest
    ports:
      - "8000:8000"  # 내부용 포트
    volumes:
      - ./.env:/app/.env
      - ~/models:/app/models
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl  # SSL 인증서 경로
    ports:
      - "443:443"  # 외부 HTTPS 요청 받기
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
