version: '3.8'

services:
  app_deploy_web:
    build: .
    container_name: app_deploy_web_1
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge 