name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yooingyu/anifarm:latest

      - name: Debug Secrets
        run: |
          echo "Checking secrets..."
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "Error: EC2_HOST is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_USERNAME }}" ]; then
            echo "Error: EC2_USERNAME is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "Error: EC2_SSH_KEY is not set"
            exit 1
          fi
          echo "All required secrets are set"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Starting deployment..."
            echo "Current directory: $(pwd)"
            echo "Creating deployment directory..."
            mkdir -p /home/ubuntu/anifarm_deploy/back
            cd /home/ubuntu/anifarm_deploy/back
            echo "Creating .env file..."
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod 600 .env
            echo "Creating docker-compose.yml file..."
            cat > docker-compose.yml << 'EOL'
            version: '3.8'

            services:
              web:
                image: yooingyu/anifarm:latest
                ports:
                  - "8000:8000"
                volumes:
                  - ./.env:/app/.env
                depends_on:
                  - db
                dns:
                  - 8.8.8.8
                  - 8.8.4.4
                networks:
                  - app-network

              db:
                image: postgres:15
                ports:
                  - "5432:5432"
                environment:
                  - POSTGRES_USER=${DB_USER}
                  - POSTGRES_PASSWORD=${DB_PASS}
                  - POSTGRES_DB=${DB_NAME}
                volumes:
                  - postgres_data:/var/lib/postgresql/data
                networks:
                  - app-network

            networks:
              app-network:
                driver: bridge

            volumes:
              postgres_data:
            EOL
            echo "Stopping existing containers..."
            docker-compose down || true
            echo "Pulling latest image..."
            docker-compose pull
            echo "Starting containers..."
            docker-compose up -d
            echo "Checking container status..."
            docker ps
            echo "Deployment completed"